const PMAB_DATA = {
  meta: {
    tagline: "Pro-Metabolic · Animal-Based · Real Food",
    philosophy: "Eat to support your metabolism and hormones. Prioritize saturated fat, ripe fruit sugar, animal protein, and mineral-dense whole foods. The framework is defined by what it includes — not what it excludes.",
  },

  categories: [
    {
      id: "meat",
      label: "Meat & Organs",
      emoji: "🥩",
      color: "#9B2335",
      note: "Ruminants first. Organs weekly. Balance muscle meat with gelatin or broth — glycine offsets methionine.",
      items: [
        { name: "Grass-fed beef — ground, ribeye, chuck, brisket", note: "Daily staple. Saturated fat, heme iron, zinc, B12, creatine.", starred: true },
        { name: "Beef liver", note: "Peat + Saladino both prioritize this. Retinol, copper, folate, B12. Once or twice weekly.", starred: true },
        { name: "Beef heart", note: "Highest CoQ10 of any food. Tastes like steak, far cheaper than ribeye." },
        { name: "Beef kidney", note: "Selenium, B12, riboflavin — often overlooked, easy to braise." },
        { name: "Beef tongue", note: "Rich in collagen and zinc. Saladino staple. Slow cook then pan-sear." },
        { name: "Bone marrow", note: "Alkylglycerols, fat-soluble vitamins, deeply satisfying saturated fat." },
        { name: "Suet / beef tallow (rendered)", note: "Saladino's preferred cooking fat. Pure saturated fat, nearly zero PUFA." },
        { name: "Lamb — chops, shoulder, rack, leg", note: "CLA-rich, highly digestible. Grass-finished standard in much of the world.", starred: true },
        { name: "Lamb liver", note: "Milder flavor than beef liver — good entry point for organ newcomers." },
        { name: "Bison", note: "Ruminant, leaner than beef. Grass-finished virtually always." },
        { name: "Venison / elk", note: "Wild ruminant — clean, mineral-rich, near-zero PUFA." },
        { name: "Pork (pasture-raised)", note: "Ribs, shoulder, belly. Higher PUFA than ruminant but tolerable if pasture-raised." },
        { name: "Oysters (fresh or canned)", note: "Highest zinc food on earth. Both Peat and Saladino explicitly recommend. 4–6 weekly minimum.", starred: true },
        { name: "Shrimp", note: "Iodine, selenium, astaxanthin. Fast-digesting, low PUFA, extremely versatile." },
        { name: "Crab (Dungeness, king, snow)", note: "Zinc, selenium, B12. Low PUFA. Pairs perfectly with butter." },
        { name: "Lobster", note: "High protein, low PUFA, rich in iodine and selenium." },
        { name: "Clams", note: "Extraordinary B12 concentration. Also iron, potassium, selenium." },
        { name: "Mussels", note: "Omega-3 ratio is favorable. Zinc, manganese, selenium." },
        { name: "White fish — cod, sole, halibut, flounder", note: "Peat-approved seafood. Low PUFA, clean protein. Wild-caught only." },
        { name: "Canned oysters (smoked or plain)", note: "Convenient zinc source. Crown Prince or Bar Harbor brand — no seed oils." },
        { name: "Bone broth (homemade)", note: "Glycine, proline, collagen. Peat's preferred protein offset for muscle meat. Use daily.", starred: true },
        { name: "Gelatinous cuts — oxtail, short rib, shank, cheek", note: "Natural collagen delivery. Low-and-slow cook unlocks gelatin.", starred: true },
      ]
    },
    {
      id: "dairy",
      label: "Dairy",
      emoji: "🥛",
      color: "#2C5F8A",
      note: "Full-fat only. Raw or low-temp pasteurized preferred. A2 casein preferred. Peat treated milk as food — not just a drink.",
      items: [
        { name: "Whole milk — raw, A2, or grass-fed", note: "Peat's cornerstone food. Calcium, potassium, phosphorus, lactose. 1–2 quarts daily is Peat-normal.", starred: true },
        { name: "Aged hard cheese — cheddar, parmesan, gruyère, gouda", note: "K2 (MK-4), fat-soluble vitamins, complete protein. Low-lactose. Daily snack.", starred: true },
        { name: "Salted butter (grass-fed)", note: "Butyrate, K2, short-chain saturated fats. Peat and Saladino both use freely.", starred: true },
        { name: "Heavy cream", note: "Almost pure fat. Add to coffee, cook with it, whip with honey." },
        { name: "Whole milk yogurt — plain, full-fat", note: "Live cultures, good protein. Peat-tolerated. Pair with fruit." },
        { name: "Full-fat cottage cheese", note: "High protein, casein-based. Easy digestion. Mix with fruit or honey." },
        { name: "Ricotta (whole milk)", note: "Mild, whey-based. Good with honey and tropical fruit." },
        { name: "Raw goat milk or cheese", note: "A2 casein naturally. Often better tolerated than cow A1 for sensitive individuals." },
        { name: "Kefir (whole milk)", note: "Broader probiotic spectrum than yogurt. Good potassium and calcium profile." },
        { name: "Ice cream — minimal ingredients", note: "Peat explicitly approved: cream + sugar + egg yolk = pro-metabolic dessert. Read labels: no seed oils.", starred: true },
        { name: "Ghee", note: "Clarified butter — pure butterfat, casein-free. High smoke point for cooking." },
        { name: "Crème fraîche / sour cream", note: "Fermented cream. Full fat. Good as a sauce base or condiment." },
        { name: "Raw milk cheese — aged 60+ days", note: "Legal in US. Complex flavor, K2-rich. Parmesan Reggiano is the benchmark." },
        { name: "Whipped cream (unsweetened)", note: "Heavy cream only. Sweeten with honey. Goes with everything fruit-based." },
      ]
    },
    {
      id: "fruit",
      label: "Fruit & Natural Sugar",
      emoji: "🍊",
      color: "#C96A1A",
      note: "Primary carbohydrate source. Must be ripe. Juice is encouraged — Peat drank OJ daily. Saladino targets 150–300g carbs/day from fruit and honey.",
      items: [
        { name: "Fresh-squeezed orange juice", note: "Peat's daily ritual. Potassium, vitamin C, folic acid, easily-used sugar. The single most Peat-aligned food.", starred: true },
        { name: "Ripe mango", note: "Dense sucrose, beta-carotene, B6. Saladino eats watermelon + mango daily.", starred: true },
        { name: "Watermelon", note: "Lycopene, citrulline, potassium. High water content. Saladino's daily fruit.", starred: true },
        { name: "Ripe papaya", note: "Papain enzymes, lycopene, easy carbs. Peat approved. Eat fully ripe." },
        { name: "Ripe banana", note: "Potassium powerhouse. Must be fully ripe (brown-speckled). Resistant starch when green — that's fine too." },
        { name: "Cherries (sweet or tart)", note: "Anti-inflammatory, melatonin, anthocyanins. Low PUFA. Easy to overeat — do it." },
        { name: "Ripe pineapple", note: "Bromelain, manganese, vitamin C. Excellent fresh or grilled." },
        { name: "Melon — cantaloupe, honeydew, casaba", note: "Hydrating, beta-carotene (cantaloupe), potassium. Eat with salt." },
        { name: "Grapes", note: "Peat mentions grapes specifically. Resveratrol, quick sugar, easy snacking." },
        { name: "Dates (medjool)", note: "Concentrated sucrose + minerals. Sweetener, energy boost, pair with cheese.", starred: true },
        { name: "Peaches / nectarines", note: "In-season summer staple. Ripe only. High in potassium." },
        { name: "Apricots (fresh or dried)", note: "Beta-carotene, potassium. Dried apricots are a good travel/snack option — no sulfur dioxide." },
        { name: "Figs (fresh or dried)", note: "Calcium, potassium, quick sugar. Saladino-compatible. Pair with cheese." },
        { name: "Berries — strawberries, blueberries, blackberries", note: "Antioxidants, lower sugar load. Saladino includes these as low-toxicity fruit." },
        { name: "Pomegranate / pomegranate juice", note: "Punicalagins, potassium, nitrates. Pro-metabolic and anti-estrogenic per Peat." },
        { name: "Guava", note: "Exceptionally high vitamin C, lycopene, potassium. Tropical Peat staple." },
        { name: "Lychee", note: "Peat mentions tropical fruits. High vitamin C, easy sugar." },
        { name: "Coconut water (pure, no additives)", note: "Electrolytes: potassium, magnesium, sodium. Good post-exercise. Read labels carefully." },
        { name: "Raw honey", note: "Peat's preferred sweetener. Fructose + glucose + trace enzymes. Add to milk, coffee, yogurt.", starred: true },
        { name: "Cane sugar (organic white or unrefined)", note: "Peat explicitly included white sugar. Sucrose splits to glucose + fructose. Pro-metabolic when not displacing whole food." },
        { name: "Maple syrup (Grade A or B, pure)", note: "Sucrose-based, manganese, some minerals. Better than agave or HFCS." },
        { name: "Fruit jams / preserves (no pectin, minimal ingredients)", note: "Peat mentioned canned fruit and jams as acceptable. Check for seed oils." },
        { name: "Canned fruit in light syrup or juice", note: "Peat-endorsed convenience option when fresh isn't available." },
      ]
    },
    {
      id: "eggs",
      label: "Eggs",
      emoji: "🥚",
      color: "#7A6A2A",
      note: "Whole eggs — yolk is the primary value. Pasture-raised preferred for K2 and carotenoids. Both Peat and Saladino include daily.",
      items: [
        { name: "Pasture-raised whole eggs", note: "Complete protein, choline (essential for liver), K2, lutein, cholesterol precursors. Daily staple.", starred: true },
        { name: "Egg yolks only", note: "Pure fat-soluble vitamins — A, D, K2, E — plus choline. Skip whites if digestive issues." },
        { name: "Duck eggs", note: "Larger yolk, richer flavor, more fat-soluble vitamins than chicken eggs." },
      ]
    },
    {
      id: "fats",
      label: "Fats & Oils",
      emoji: "🧈",
      color: "#5C4A1E",
      note: "Saturated fats for cooking. Zero seed oils, ever. Cold-pressed olive oil in moderation. Fat quality matters as much as fat type.",
      items: [
        { name: "Butter (grass-fed, salted)", note: "The foundational cooking fat. Butyrate, CLA, K2, short-chain saturated fats.", starred: true },
        { name: "Beef tallow (rendered)", note: "Saladino's primary cooking fat. Beef fat profile, high smoke point, neutral flavor.", starred: true },
        { name: "Coconut oil (refined or virgin)", note: "MCTs, lauric acid, near-zero PUFA. High smoke point. Peat recommended.", starred: true },
        { name: "Ghee", note: "Clarified butter — no casein, pure butterfat. Very high smoke point." },
        { name: "Lard (pasture-raised pork fat)", note: "High smoke point, mostly saturated/monounsaturated. Old-school frying fat." },
        { name: "Lamb fat / lamb tallow", note: "Similar to beef tallow. Excellent for roasting vegetables or basting." },
        { name: "Cocoa butter", note: "Baking fat. Stearic acid dominant — nearly zero PUFA. Great in homemade chocolate." },
        { name: "Extra virgin olive oil (cold use only)", note: "Drizzle and dressings. Peat allowed in moderation. Never heat above medium." },
        { name: "Macadamia nut oil", note: "Peat mentioned this — highest monounsaturated content of any oil, very low PUFA." },
      ]
    },
    {
      id: "roots",
      label: "Roots, Tubers & Cooked Starches",
      emoji: "🥕",
      color: "#4A7A3A",
      note: "Always cooked. Roots and tubers are the preferred plant carbs in this framework. Pair starches with saturated fat for stability.",
      items: [
        { name: "White potato (boiled, baked, or mashed)", note: "Potassium (more than banana), safe starch. Peat approved. Skin optional.", starred: true },
        { name: "Sweet potato / yam", note: "Beta-carotene, easy digestion, potassium. Roast or steam." },
        { name: "Raw grated carrot (Peat's raw carrot salad)", note: "Peat's unique recommendation. Binds endotoxins and excess estrogen in the gut. 1 raw carrot daily with coconut oil + salt.", starred: true },
        { name: "Beets (cooked)", note: "Nitrates, folate, betaine for liver support." },
        { name: "Turnips / rutabaga", note: "Low-starch root. Roast with butter." },
        { name: "Parsnips", note: "Sweet, starchy root. Pairs well with meat." },
        { name: "White rice (well-cooked)", note: "Cleanest grain — no antinutrients, easy digestion, neutral flavor. Peat included.", starred: true },
        { name: "Corn tortillas (masa harina)", note: "Nixtamalized corn — Peat forum staple. Low PUFA. Better starch tolerance than wheat." },
        { name: "Cooked butternut squash / delicata / acorn", note: "Saladino includes squash. Sweet, low-toxin, mineral-decent." },
        { name: "Cassava / yuca (well-cooked)", note: "Dense resistant starch. Must be thoroughly cooked. Popular in Saladino animal-based community." },
        { name: "Mushrooms (well-cooked)", note: "B vitamins, ergothioneine, beta-glucans. Always cook thoroughly." },
        { name: "Cooked asparagus", note: "Saladino's list includes this. Prebiotic fiber, folate, potassium." },
        { name: "Cooked zucchini / summer squash", note: "Mild, low-toxin, versatile. Cook soft." },
      ]
    },
    {
      id: "drinks",
      label: "Drinks & Beverages",
      emoji: "☕",
      color: "#3D2B1A",
      note: "Peat: hydrate via milk, juice, and fruit rather than plain water. Coffee is explicitly pro-metabolic. Avoid plain water in excess — add salt or juice.",
      items: [
        { name: "Coffee (black or with milk + sugar)", note: "Peat's most consistent recommendation. Anti-estrogenic, pro-thyroid, liver-protective. Add milk and sugar — not oat milk.", starred: true },
        { name: "Fresh-squeezed orange juice", note: "Peat's primary hydration vehicle. Not from concentrate, no additives.", starred: true },
        { name: "Whole milk (as beverage)", note: "Peat reportedly drank up to 2–3 quarts daily. Calcium + phosphorus ratio is ideal.", starred: true },
        { name: "Bone broth (homemade, salted)", note: "Glycine, minerals, hydration. Add salt freely. Sip like tea." },
        { name: "Gelatin in juice or milk", note: "Stir Great Lakes or Knox gelatin into OJ or milk. Peat's glycine delivery method.", starred: true },
        { name: "Coconut water (pure)", note: "Electrolyte drink. Potassium, magnesium, natural sugars. Post-activity." },
        { name: "Whole milk kefir", note: "Fermented, probiotic-rich. Count as milk intake, not separate category." },
        { name: "Herbal tea (chamomile, ginger, hibiscus)", note: "Peat tolerated herbal teas. Hibiscus is anti-estrogenic." },
        { name: "Pomegranate juice (pure)", note: "Anti-estrogenic, high in antioxidants. Peat-aligned." },
        { name: "Grape juice (pure, no additives)", note: "Peat mentioned grape juice as acceptable sugar source." },
        { name: "Salted water or mineral water", note: "When drinking plain water, add a pinch of salt. Peat emphasized sodium for metabolic rate." },
        { name: "Cane sugar soda (Mexican Coke, pure cane)", note: "Peat explicitly mentioned this — quick sucrose, CO2. Not a daily habit but not vilified." },
        { name: "Raw milk (if available)", note: "Saladino's preference. Undenatured whey proteins, enzymes intact." },
      ]
    },
    {
      id: "functional",
      label: "Functional & Specialty Foods",
      emoji: "⚗️",
      color: "#3A4A6A",
      note: "Foods with targeted benefits beyond basic nutrition — Peat wrote extensively on several of these.",
      items: [
        { name: "Gelatin powder (Great Lakes, unflavored)", note: "Peat's top supplement-level food. Glycine + proline — balance muscle meat amino acids. Add to any liquid.", starred: true },
        { name: "Collagen peptides (hydrolyzed)", note: "More soluble than gelatin. Same amino acid profile. Dissolves in cold liquid." },
        { name: "Raw carrot (daily)", note: "Peat's unique protocol. Insoluble fiber + antibacterial compounds reduce gut endotoxin load.", starred: true },
        { name: "Homemade gelatin gummies", note: "OJ + gelatin + honey. Community staple for hitting glycine goals tastefully." },
        { name: "Pork rinds / chicharones (pure, salt only)", note: "Peat mentioned these as a PUFA-free snack. Look for lard-fried, no seed oils." },
        { name: "Dark chocolate 85%+ (cacao, cocoa butter, sugar)", note: "Saladino includes this. Magnesium, stearic acid, flavanols. Read labels — no soy lecithin." },
        { name: "Cacao powder (raw or Dutch process)", note: "Magnesium, iron, theobromine. Add to milk with honey." },
        { name: "Coconut meat / dried coconut (unsweetened)", note: "Saturated fat, MCTs, fiber. Peat approved." },
        { name: "Sea salt (unrefined)", note: "Peat emphasized adequate salt intake for metabolic rate and thyroid. Salt food freely.", starred: true },
        { name: "Oyster sauce or fish sauce (clean label)", note: "Umami without seed oil. Trace minerals. Read ingredients — some brands add sugar or MSG." },
        { name: "Bee pollen", note: "Saladino has included this — minerals, enzymes, B vitamins." },
        { name: "Mineral water (high magnesium)", note: "Peat valued magnesium. Gerolsteiner or Topo Chico as sparkling options." },
      ]
    },
    {
      id: "supplements",
      label: "Supplements & Add-Ons",
      emoji: "💊",
      color: "#4A2A6A",
      note: "Both Peat and Saladino are food-first. Supplements fill genuine gaps — especially thyroid function, mineral balance, and fat-soluble vitamins.",
      items: [
        { name: "Magnesium glycinate or bicarbonate", note: "Widespread modern deficiency. Critical for thyroid conversion, energy, sleep. Peat preferred bicarbonate form.", starred: true },
        { name: "Vitamin K2 (MK-4 form, high dose)", note: "Synergistic with D3 — directs calcium to bone, not arteries. Grass-fed dairy helps but supplementing is reliable." },
        { name: "Vitamin D3 (with K2)", note: "If limited sun. Saladino sun-focuses over supplementing, but D3 is acceptable gap-filler. Test before high-dosing." },
        { name: "Vitamin E (mixed tocopherols)", note: "Peat recommended — anti-estrogenic, protects against PUFA oxidation, supports thyroid." },
        { name: "Vitamin A (retinol, from liver or supplement)", note: "Peat and Saladino both emphasize preformed retinol over beta-carotene. Liver is the best source." },
        { name: "Iodine (Lugol's solution or kelp)", note: "Thyroid substrate. Essential. Peat and Saladino both reference iodine needs. Dose carefully — more isn't better." },
        { name: "Selenium (Brazil nuts or supplement)", note: "Thyroid enzyme cofactor. Works synergistically with iodine. 1–2 Brazil nuts daily." },
        { name: "Thiamine / B1 (high dose per TTFD research)", note: "Peat-aligned community increasingly uses B1 for energy metabolism. Often deficient in high-carb eaters." },
        { name: "Zinc (supplement or oysters)", note: "Saladino emphasizes zinc constantly. If not eating oysters 2x weekly, supplement." },
        { name: "Copper (liver or supplement)", note: "Balance with zinc. Liver is ideal food source. Peat valued copper for thyroid + energy." },
        { name: "Collagen peptides / gelatin (food-supplement hybrid)", note: "Glycine is anti-aging, anti-stress, liver-protective. 10–20g daily from food or powder.", starred: true },
        { name: "Progesterone (topical, research-grade)", note: "Peat's most discussed hormonal intervention. Anti-estrogen, pro-thyroid. Research required — not casual." },
        { name: "Aspirin (low-dose, baby)", note: "Peat endorsed: anti-inflammatory, anti-endotoxin, uncouples mitochondria. Not for everyone — research context." },
        { name: "Methylene blue (low dose, pharmaceutical grade)", note: "Emerging Peat-adjacent bioenergetics topic. Mitochondrial electron carrier. Requires careful research." },
      ]
    },
  ]
};
