const FOODS_DB = [
  {
    id: "beef",
    name: "Grass-Fed Beef",
    emoji: "🥩",
    category: "meat",
    score: 96,
    verdict: "Cornerstone food",
    verdictType: "yes",
    tags: ["foundation","daily","highfat","highpro"],
    peat: { rating: "strong-yes", summary: "Peat consistently recommended beef as the primary protein source. Emphasizes the importance of gelatin/broth alongside muscle meat to balance methionine with glycine. Favors fattier cuts." },
    saladino: { rating: "strong-yes", summary: "The flagship Saladino food. Ribeye is his most-recommended cut. Advocates grass-finished for better fat profile — higher CLA, lower PUFA. Organ meats from the same animal ideally." },
    pmab: "The clearest area of agreement in the entire framework. Eat beef, ideally grass-finished, ideally fattier cuts, ideally with broth or gelatinous cuts alongside. Foundation-tier, daily.",
    nutrients: ["Complete protein","Heme iron","Zinc","B12","Creatine","Saturated fat"],
    concerns: ["Balance muscle meat with gelatin/glycine","Avoid overcooking"]
  },
  {
    id: "liver",
    name: "Beef Liver",
    emoji: "🫀",
    category: "organs",
    score: 94,
    verdict: "Weekly non-negotiable",
    verdictType: "yes",
    tags: ["organs","weekly"],
    peat: { rating: "yes", summary: "Peat recommended liver but cautioned against excess — particularly around retinol toxicity at very high doses. Once or twice weekly is his general guidance. Calf liver preferred for milder flavor and slightly lower iron." },
    saladino: { rating: "strong-yes", summary: "Saladino calls liver 'nature's multivitamin' and considers it the single most nutrient-dense food available. Weekly consumption is non-negotiable in his protocol. Beef liver specifically for highest retinol content." },
    pmab: "Both agree: liver weekly. Peat's caution on excess is worth noting — 3–4 oz once or twice a week is sufficient. The nutrient delivery in that portion (retinol, copper, folate, B12) is unmatched by any other food.",
    nutrients: ["Retinol (Vitamin A)","Copper","Folate","B12","Iron","CoQ10"],
    concerns: ["Excess retinol at very high doses","High in iron — balance with calcium-rich foods"]
  },
  {
    id: "whole-milk",
    name: "Whole Milk",
    emoji: "🥛",
    category: "dairy",
    score: 91,
    verdict: "Peat's cornerstone — tolerate and prioritize",
    verdictType: "yes",
    tags: ["dairy","daily","peat-core"],
    peat: { rating: "strong-yes", summary: "Milk is arguably Peat's single most recommended food. He reportedly consumed 1–2 quarts daily. The calcium-phosphorus ratio supports metabolic rate, lactose provides quick glucose, and the fat content delivers short-chain saturated fats and butyrate. Raw or low-temp pasteurized preferred." },
    saladino: { rating: "mixed", summary: "Saladino includes dairy but acknowledges individual variation. Raw A2 milk is his preference. Acknowledges that many people tolerate dairy well, but it's not universally emphasized the way it is in Peat's framework." },
    pmab: "If you tolerate dairy, whole milk is one of the highest-leverage foods in the framework. The Peat case is strong: calcium, pro-metabolic lactose, short-chain fats. Raw or A2 for those with sensitivity. Don't replace it with alternatives.",
    nutrients: ["Calcium","Phosphorus","Potassium","Lactose","Short-chain saturated fat","B2 (Riboflavin)"],
    concerns: ["A1 casein sensitivity in some people","Raw milk availability varies by state"]
  },
  {
    id: "orange-juice",
    name: "Orange Juice",
    emoji: "🍊",
    category: "fruit",
    score: 90,
    verdict: "Peat's daily ritual — drink it",
    verdictType: "yes",
    tags: ["fruit","daily","peat-core"],
    peat: { rating: "strong-yes", summary: "OJ was Peat's most consistently recommended beverage. Fresh-squeezed daily. Provides folic acid, potassium, and easily absorbed sugar that supports thyroid hormone conversion. Explicitly anti-estrogenic properties cited. Not from concentrate — carton OJ loses much of the benefit." },
    saladino: { rating: "yes", summary: "Saladino includes OJ as a pro-metabolic carbohydrate source. Fruit juice was controversial in early animal-based circles but Saladino shifted to supporting it as he moved away from strict carnivore." },
    pmab: "Fresh-squeezed OJ daily is a practical implementation of Peat's pro-metabolic carbohydrate thesis. Start with 8 oz, work up. Add a pinch of salt. Add gelatin for a glycine hit. One of the easiest framework wins.",
    nutrients: ["Vitamin C","Folate","Potassium","Hesperidin","Natural sucrose + glucose"],
    concerns: ["Not from concentrate","Avoid if fructose-sensitive (test individually)","Teeth — rinse after"]
  },
  {
    id: "oysters",
    name: "Oysters",
    emoji: "🦪",
    category: "shellfish",
    score: 95,
    verdict: "Highest zinc food on earth — eat them weekly",
    verdictType: "yes",
    tags: ["shellfish","weekly","organs-equivalent"],
    peat: { rating: "strong-yes", summary: "Peat explicitly recommended shellfish, especially oysters, for zinc and copper content. He saw shellfish as occupying a similar nutritional tier to organ meats — extraordinary density in a small serving." },
    saladino: { rating: "strong-yes", summary: "Oysters are one of Saladino's top recommended foods. He frames them as the highest-zinc food available and often calls them 'nature's zinc supplement.' Recommends eating them multiple times weekly." },
    pmab: "The most unanimous verdict in the framework. Oysters provide zinc (10–15x more per serving than any plant food), copper, selenium, B12, and iodine. Fresh, smoked canned (Crown Prince in water or olive oil), or frozen — all work. 4–6 weekly minimum.",
    nutrients: ["Zinc (exceptional)","Copper","Selenium","B12","Iodine","Taurine"],
    concerns: ["Canned: avoid brands using seed oils","Raw oysters — minimal food safety risk, cook if immune-compromised"]
  },
  {
    id: "butter",
    name: "Grass-Fed Butter",
    emoji: "🧈",
    category: "fats",
    score: 93,
    verdict: "Primary cooking fat — use freely",
    verdictType: "yes",
    tags: ["fat","daily","foundation"],
    peat: { rating: "strong-yes", summary: "Butter was Peat's primary cooking fat. Butyrate (a short-chain fatty acid in butter) is anti-inflammatory and feeds colonocytes. K2 content is significant in grass-fed varieties. Stable at cooking temperatures unlike any PUFA oil." },
    saladino: { rating: "strong-yes", summary: "Grass-fed butter is a Saladino staple. He specifically calls out K2 content from grass-fed cows and the saturated fat profile. Used generously in cooking and on all foods." },
    pmab: "Use butter as your default cooking fat alongside tallow. Grass-fed (Kerrygold, Vital Farms) meaningfully increases K2 content. Salted is fine — Peat emphasized adequate sodium for metabolic function.",
    nutrients: ["Butyrate","Vitamin K2 (MK-4)","Vitamin A","Short-chain saturated fats","CLA (grass-fed)"],
    concerns: ["Quality matters — conventional butter has minimal K2","Store-bought ghee often lacks the butyrate benefit"]
  },
  {
    id: "tallow",
    name: "Beef Tallow",
    emoji: "🫙",
    category: "fats",
    score: 92,
    verdict: "Best high-heat cooking fat",
    verdictType: "yes",
    tags: ["fat","daily","saladino-core"],
    peat: { rating: "yes", summary: "Peat recommended saturated fats for cooking. Tallow fits his framework as a stable, nearly PUFA-free fat. Not as frequently mentioned as butter or coconut oil, but fully aligned." },
    saladino: { rating: "strong-yes", summary: "Tallow is Saladino's primary cooking fat. He sells his own brand and considers it the most ancestrally coherent cooking fat — what would have been rendered from the same animal being eaten." },
    pmab: "For high-heat cooking (searing, frying, roasting), tallow is the best choice. Higher smoke point than butter, pure saturated fat, nearly zero PUFA. Render your own from beef fat trimmings or buy pre-rendered.",
    nutrients: ["Saturated fat (oleic, stearic, palmitic)","Fat-soluble vitamins (A,D,K2 if grass-fed)","Zero PUFA"],
    concerns: ["Source matters — grass-finished has better vitamin profile","Beef tallow, not 'vegetable shortening' which is often PUFA"]
  },
  {
    id: "eggs",
    name: "Pasture-Raised Eggs",
    emoji: "🥚",
    category: "protein",
    score: 92,
    verdict: "Daily staple — yolks are the point",
    verdictType: "yes",
    tags: ["protein","daily","foundation"],
    peat: { rating: "strong-yes", summary: "Whole eggs are a Peat staple. He emphasized the yolk specifically — fat-soluble vitamins, cholesterol as a hormone precursor, choline for liver health. 2–4 daily is common in Peat-influenced protocols." },
    saladino: { rating: "strong-yes", summary: "Whole eggs are in Saladino's core food list. Pasture-raised for the carotenoid-rich yolk (lutein, zeaxanthin, beta-carotene visible as deeper orange color). He eats them daily." },
    pmab: "Eat whole eggs. Yolks are where 90% of the value is. Scrambled low-and-slow in butter, fried in tallow, or soft-boiled. Pasture-raised meaningfully increases K2 and carotenoid content. Don't eat whites without yolks.",
    nutrients: ["Choline","Lecithin","Vitamin A (retinol in yolk)","Vitamin K2","Lutein/Zeaxanthin","Complete protein"],
    concerns: ["Egg whites alone (without yolks) deplete biotin","Conventional eggs have pale yolks and minimal K2"]
  },
  {
    id: "raw-honey",
    name: "Raw Honey",
    emoji: "🍯",
    category: "sweetener",
    score: 87,
    verdict: "Best sweetener in the framework",
    verdictType: "yes",
    tags: ["sweetener","daily","fruit-category"],
    peat: { rating: "strong-yes", summary: "Peat approved honey as a pro-metabolic sweetener. The fructose-glucose ratio supports liver glycogen and thyroid function. Raw honey additionally contains enzymes, trace minerals, and antimicrobial compounds. Used in OJ, milk, and as a general sweetener." },
    saladino: { rating: "strong-yes", summary: "Honey is Saladino's preferred sweetener — explicitly endorsed in his updated animal-based framework. He views it as evolutionarily coherent (primates seek it out) and uses it daily." },
    pmab: "Use raw honey freely. Stir into OJ, milk, yogurt, coffee. Use it in cooking. It's the right sweetener for this framework — fructose and glucose in a whole-food matrix with trace nutrients.",
    nutrients: ["Glucose + fructose (1:1 ratio)","Trace minerals","Enzymes","Antimicrobial compounds (raw only)"],
    concerns: ["Pasteurized honey loses enzyme benefit — buy raw","Infants under 1 year — botulism risk, do not use"]
  },
  {
    id: "white-rice",
    name: "White Rice",
    emoji: "🍚",
    category: "starch",
    score: 80,
    verdict: "Cleanest grain — use as a starch vehicle",
    verdictType: "yes",
    tags: ["starch","daily","peat-approved"],
    peat: { rating: "yes", summary: "Peat included white rice as a pro-metabolic starch. Stripping the bran removes phytic acid and other antinutrients, leaving essentially pure digestible starch. Easy on the gut, pairs with everything." },
    saladino: { rating: "mixed", summary: "Saladino acknowledges white rice as among the better grain options but doesn't strongly emphasize it. Fruit and honey are preferred carb sources. Rice is acceptable in his framework, particularly for those needing starch." },
    pmab: "If you need starch beyond tubers, white rice is the right choice. No meaningful antinutrients, extremely gentle on digestion, neutral flavor. Cook in bone broth for added glycine. Don't overthink it.",
    nutrients: ["Digestible starch","Trace B vitamins (fortified)","Very low in everything else — that's fine"],
    concerns: ["Arsenic content — vary rice sources, rinse well","Nutritionally sparse — it's a starch vehicle, not a nutrient food"]
  },
  {
    id: "potatoes",
    name: "White Potato",
    emoji: "🥔",
    category: "starch",
    score: 85,
    verdict: "Best starch option — high potassium",
    verdictType: "yes",
    tags: ["starch","daily"],
    peat: { rating: "yes", summary: "Peat included potatoes as a pro-metabolic food. Well-cooked, the starch is highly digestible. The potassium content (higher per gram than bananas) is useful. He emphasized cooking thoroughly and noted that cooling after cooking increases resistant starch." },
    saladino: { rating: "yes", summary: "Potatoes are in Saladino's recommended food list. The anti-nutrient concern (solanine in green/sprouted potatoes) doesn't apply to properly stored and cooked potatoes. High potassium, easy digestion." },
    pmab: "Boiled, baked, or fried in tallow or coconut oil. Always cook thoroughly. One of the best potassium sources in the framework — important for electrolyte balance. Peel if concerned about solanine; it concentrates in the skin.",
    nutrients: ["Potassium (exceptional)","Vitamin C","B6","Digestible starch"],
    concerns: ["Green or sprouted potatoes — solanine, discard","Always cook thoroughly — raw potato starch is problematic"]
  },
  {
    id: "coconut-oil",
    name: "Coconut Oil",
    emoji: "🥥",
    category: "fats",
    score: 84,
    verdict: "Good cooking fat — MCT benefits",
    verdictType: "yes",
    tags: ["fat","daily"],
    peat: { rating: "strong-yes", summary: "Peat was an early and strong advocate for coconut oil — specifically citing lauric acid and medium-chain triglycerides as protective against the thyroid-suppressing effects of PUFA. He recommended it for cooking and as a supplement to displace PUFA in tissue over time." },
    saladino: { rating: "yes", summary: "Coconut oil is acceptable in Saladino's framework but less emphasized than animal fats. Useful for cooking, baking, and situations where butter or tallow isn't available." },
    pmab: "Good cooking fat, especially for medium-heat applications. The MCT content is real and useful. Use refined coconut oil for cooking (neutral flavor, higher smoke point) and virgin for cold applications. Not a replacement for butter or tallow — use alongside.",
    nutrients: ["Lauric acid","MCTs (medium-chain triglycerides)","Near-zero PUFA"],
    concerns: ["Refined vs. virgin matters for smoke point","Less nutritionally complete than animal fats — use alongside, not instead"]
  },
  {
    id: "mango",
    name: "Ripe Mango",
    emoji: "🥭",
    category: "fruit",
    score: 88,
    verdict: "Best tropical fruit — eat ripe and daily",
    verdictType: "yes",
    tags: ["fruit","daily"],
    peat: { rating: "strong-yes", summary: "Peat included tropical fruits as pro-metabolic carbohydrate sources. Mango's high sucrose content is favorable — it splits cleanly into glucose and fructose. Beta-carotene content and the enzyme profile of ripe mango are additional benefits." },
    saladino: { rating: "strong-yes", summary: "Mango is one of Saladino's most frequently mentioned fruits. He eats watermelon and mango daily. The ripe version specifically — fully yellow-orange, sweet throughout, not firm green." },
    pmab: "One of the most nutrient-dense fruits in the framework. Buy ripe (fully yellow-orange) or ripen at room temperature. The sucrose content supports thyroid function. Pair with dairy for calcium alongside natural sugar — a Peat-specific pairing.",
    nutrients: ["Sucrose","Beta-carotene","Vitamin C","B6","Folate","Potassium"],
    concerns: ["Unripe mango is high in resistant starch — wait until fully ripe","Imported mango often gassed — ripen naturally at home"]
  },
  {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    category: "beverage",
    score: 85,
    verdict: "Pro-metabolic daily habit — drink with milk",
    verdictType: "yes",
    tags: ["beverage","daily","peat-core"],
    peat: { rating: "strong-yes", summary: "One of Peat's most consistent recommendations. Coffee is anti-estrogenic, stimulates bile flow, protects the liver, and is pro-thyroid when consumed in context. He emphasized drinking it with milk and sugar — not black — to buffer the cortisol response and provide calcium alongside the stimulant effect." },
    saladino: { rating: "mixed", summary: "Saladino has a more nuanced view on coffee. He acknowledges the benefits but is cautious about cortisol elevation and individual sensitivity. For those who tolerate it well, he doesn't discourage it." },
    pmab: "Coffee with whole milk and a teaspoon of honey or sugar is the Peat protocol implementation. The calcium from milk buffers the cortisol response. Add collagen peptides or gelatin for glycine. Drink 1–3 cups in the morning, not after noon.",
    nutrients: ["Chlorogenic acids","Magnesium","B3 (Niacin)","Polyphenols"],
    concerns: ["Black coffee on empty stomach raises cortisol — always have with milk and food","After noon — disrupts sleep architecture","Individual sensitivity varies significantly"]
  },
  {
    id: "bone-broth",
    name: "Homemade Bone Broth",
    emoji: "🍲",
    category: "functional",
    score: 91,
    verdict: "Non-negotiable glycine source — make it weekly",
    verdictType: "yes",
    tags: ["functional","daily","gelatin"],
    peat: { rating: "strong-yes", summary: "Peat's glycine thesis makes bone broth one of his most important food recommendations. Gelatin from slow-cooked bones delivers glycine and proline that balance the methionine in muscle meat. He treated it as functional food — not just soup. Should gel solid when refrigerated." },
    saladino: { rating: "yes", summary: "Bone broth is in Saladino's nose-to-tail framework as a logical complement to muscle meat. He acknowledges the glycine-methionine balance argument and recommends it regularly." },
    pmab: "Make a batch every 1–2 weeks. Use knuckle bones, feet, and oxtail for maximum gelatin content. Should gel solid when chilled — that's the test. Salt aggressively. Drink as a beverage or cook everything in it. The glycine content justifies the effort.",
    nutrients: ["Glycine","Proline","Collagen-derived peptides","Calcium","Magnesium","Phosphorus"],
    concerns: ["Store-bought broth rarely gels — usually insufficient collagen","Lead content concern — use organic/pastured bones","Histamine sensitivity — fresh only, don't slow-cook over 12 hrs"]
  },
  {
    id: "kale",
    name: "Raw Kale",
    emoji: "🥬",
    category: "vegetable",
    score: 28,
    verdict: "Skip raw — limited benefit, meaningful downsides",
    verdictType: "no",
    tags: ["vegetable","avoid-raw"],
    peat: { rating: "no", summary: "Peat was explicitly critical of raw cruciferous vegetables including kale. They contain goitrogens (compounds that interfere with thyroid hormone synthesis), oxalic acid, and other antinutrients. He saw them as thyroid-suppressive and would not recommend them in any meaningful quantity, especially raw." },
    saladino: { rating: "no", summary: "Saladino categorizes kale as a high-toxin plant food. Raw kale has oxalates, goitrogens, isothiocyanates, and lectins. His animal-based framework specifically deprioritizes leafy greens like kale as nutritional foundations." },
    pmab: "Both frameworks agree: raw kale doesn't belong in a pro-metabolic diet. If you want cooked dark leafy greens, well-cooked spinach or chard (cooking neutralizes goitrogens and reduces oxalates) is a different conversation. But raw kale in a smoothie is a PMAB no.",
    nutrients: ["Vitamin K (blocked by oxalates)","Some folate (reduced bioavailability raw)"],
    concerns: ["Goitrogens — interfere with thyroid hormone synthesis","High oxalates — kidney stone risk, mineral binding","Cooking significantly reduces but doesn't eliminate concerns"]
  },
  {
    id: "almonds",
    name: "Almonds",
    emoji: "🌰",
    category: "nuts",
    score: 32,
    verdict: "Not a PMAB staple — high PUFA, high oxalate",
    verdictType: "no",
    tags: ["nuts","limit"],
    peat: { rating: "no", summary: "Peat was skeptical of nuts generally due to PUFA content. Almonds are particularly high in linoleic acid — the omega-6 PUFA most associated with PUFA accumulation in tissue. He wouldn't recommend almonds as a regular food in a pro-metabolic diet." },
    saladino: { rating: "no", summary: "Saladino categorizes almonds as a moderate-to-high toxin plant food. High in oxalates, phytic acid, and PUFA. Not included in his animal-based food list. Occasionally tolerated but not a recommended food." },
    pmab: "Both frameworks agree almonds don't belong as a staple. The linoleic acid content is the primary concern — it accumulates in tissue and suppresses thyroid over time. If you want a crunchy snack, pork rinds in lard are the PMAB-aligned alternative.",
    nutrients: ["Linoleic acid (PUFA — problematic)","Vitamin E","Magnesium (partially blocked by phytate)"],
    concerns: ["High linoleic acid — PUFA accumulation","High oxalates — mineral binding, kidney stones","Phytic acid blocks mineral absorption"]
  },
  {
    id: "salmon",
    name: "Wild Salmon",
    emoji: "🐟",
    category: "fish",
    score: 68,
    verdict: "Limit to 1–2x per week — high PUFA despite benefits",
    verdictType: "limit",
    tags: ["fish","limit","pufa"],
    peat: { rating: "limit", summary: "Peat acknowledged salmon's omega-3 benefits but cautioned about the PUFA content overall. He was specifically concerned about the PUFA accumulation that occurs with frequent consumption of high-PUFA fish. Low-PUFA white fish (cod, sole) was his preferred seafood." },
    saladino: { rating: "yes", summary: "Saladino includes wild salmon as a quality food — the omega-3 to omega-6 ratio in wild salmon is significantly better than farmed. He recommends wild-caught only and limits to a few times weekly." },
    pmab: "Wild salmon is nutritious but PUFA-heavy even by wild-caught standards. The DHA and astaxanthin content are real benefits. PMAB verdict: wild-caught, 1–2x per week maximum, not daily. If choosing regularly, low-PUFA white fish is more aligned.",
    nutrients: ["Omega-3 (EPA + DHA)","Astaxanthin","Vitamin D","Protein","Selenium"],
    concerns: ["Farmed salmon — avoid entirely (high PUFA, dye-fed)","Wild-caught still high in PUFA — don't overdo","PCBs and heavy metals in some wild populations"]
  },
  {
    id: "canola-oil",
    name: "Canola / Rapeseed Oil",
    emoji: "🚫",
    category: "seed-oil",
    score: 2,
    verdict: "Never. The clearest no in the framework.",
    verdictType: "never",
    tags: ["seed-oil","never"],
    peat: { rating: "strong-no", summary: "Peat was one of the earliest and most consistent voices against vegetable/seed oils. Canola is particularly problematic — high linoleic acid, industrial processing, hexane extraction, high-temperature refining that generates aldehydes and trans fats. He saw seed oils as among the most damaging inputs to the modern diet." },
    saladino: { rating: "strong-no", summary: "Canola oil is the most frequently cited dietary villain in Saladino's framework. The linoleic acid content accumulates in cell membranes and mitochondria over years. He considers seed oil elimination the single highest-leverage dietary change anyone can make." },
    pmab: "This is the one area of absolute, unqualified, unanimous agreement across every voice in this framework. Canola oil and all industrial seed oils are out. Read labels — it's in almost everything processed. If you make only one change, make it this.",
    nutrients: [],
    concerns: ["Highest-PUFA common cooking oil","Industrial hexane extraction","Generates toxic aldehydes when heated","Accumulates in tissue over years — the 'PUFA debt'"]
  },
  {
    id: "sourdough",
    name: "Sourdough Bread",
    emoji: "🍞",
    category: "grain",
    score: 55,
    verdict: "Context-dependent — better than conventional bread",
    verdictType: "limit",
    tags: ["grain","context","limit"],
    peat: { rating: "mixed", summary: "Peat was generally skeptical of wheat but acknowledged that fermentation reduces antinutrients. He didn't strongly recommend sourdough but didn't categorically exclude it. For those who tolerate grains, properly fermented sourdough was more acceptable than commercial bread." },
    saladino: { rating: "mixed", summary: "Saladino's view has evolved. He categorizes sourdough as better than conventional bread due to fermentation reducing lectins and phytic acid, but it's not in his core food list. Occasional rather than daily." },
    pmab: "If you eat bread, sourdough from a quality bakery (long fermentation, simple ingredients) is the best option. But it's not a foundation food. Use rice or potatoes as your primary starches. Sourdough is a 'context-dependent' food — for social eating, travel, or transition from a standard diet.",
    nutrients: ["Some B vitamins","Iron (partially blocked by phytate)","Fermentation-derived organic acids"],
    concerns: ["Gluten sensitivity — test individually","Short-fermentation commercial 'sourdough' has no antinutrient reduction","Wheat still has the highest lectin load of major grains"]
  }
];
