const MEALS_DATA = {

  categories: [
    { id: "breakfast", label: "Breakfast", emoji: "🌅" },
    { id: "lunch",     label: "Lunch",     emoji: "☀️" },
    { id: "dinner",    label: "Dinner",    emoji: "🌙" },
    { id: "snack",     label: "Snacks & Drinks", emoji: "🥛" },
    { id: "sides",     label: "Sides & Extras",  emoji: "🍚" },
  ],

  tags: [
    { id: "quick",    label: "Quick",        desc: "Under 20 min" },
    { id: "organs",   label: "Organs",       desc: "Liver, heart, kidney" },
    { id: "dairy",    label: "Dairy-heavy",  desc: "Milk, cheese, cream" },
    { id: "fruit",    label: "Fruit-forward",desc: "Peat sugar focus" },
    { id: "gelatin",  label: "Gelatin",      desc: "Glycine-rich" },
    { id: "shellfish",label: "Shellfish",    desc: "Zinc & iodine" },
    { id: "highfat",  label: "High Fat",     desc: "Saturated fat focus" },
    { id: "highpro",  label: "High Protein", desc: "Protein anchor meals" },
    { id: "saladino", label: "Saladino",     desc: "Animal-based aligned" },
    { id: "peat",     label: "Peat Core",    desc: "Classic Peat protocol" },
  ],

  meals: [
    // ── BREAKFAST ──────────────────────────────────────────
    {
      id: "b1",
      category: "breakfast",
      name: "OJ + Gelatin Coffee",
      tags: ["quick", "gelatin", "dairy", "fruit", "peat"],
      time: "5 min",
      why: "Peat's classic morning protocol. Coffee is anti-estrogenic and pro-thyroid. Gelatin in OJ delivers glycine first thing. Milk adds calcium and protein.",
      ingredients: [
        "8–12 oz fresh-squeezed orange juice",
        "1 tbsp gelatin powder (Great Lakes or Knox)",
        "1 cup coffee",
        "¼ cup whole milk or heavy cream",
        "1 tsp raw honey or cane sugar",
        "Pinch of sea salt",
      ],
      method: "Bloom gelatin in cold OJ for 1 min, then stir — it dissolves without heating. Brew coffee, add milk and sweetener. Drink both together or alternate. Add salt to the OJ.",
    },
    {
      id: "b2",
      category: "breakfast",
      name: "Butter-Scrambled Eggs with Cheese",
      tags: ["quick", "dairy", "highfat", "highpro", "peat", "saladino"],
      time: "8 min",
      why: "Whole eggs deliver choline, K2, fat-soluble vitamins. Butter-scrambled low and slow keeps yolks nutritious. Aged cheese adds K2 and calcium.",
      ingredients: [
        "3–4 pasture-raised whole eggs",
        "2 tbsp grass-fed butter",
        "1 oz aged cheddar or gruyère, grated",
        "Sea salt, pinch",
        "Optional: 1 cup whole milk on the side",
      ],
      method: "Melt butter over low heat. Add beaten eggs. Stir constantly with spatula — keep heat low the whole time. Pull off heat while still slightly wet. Top with cheese immediately.",
    },
    {
      id: "b3",
      category: "breakfast",
      name: "Tropical Fruit Bowl with Honey & Cream",
      tags: ["quick", "fruit", "dairy", "peat", "saladino"],
      time: "5 min",
      why: "Ripe mango, papaya, and pineapple provide dense sucrose and fructose, digestive enzymes, and beta-carotene. Heavy cream adds fat to slow sugar absorption.",
      ingredients: [
        "1 ripe mango, cubed",
        "½ ripe papaya, cubed",
        "½ cup ripe pineapple chunks",
        "2 tbsp raw honey",
        "3 tbsp heavy cream or whole milk yogurt",
        "Squeeze of lime",
      ],
      method: "Combine fruit in a bowl. Drizzle honey, spoon over cream or yogurt. Add lime. Eat immediately — ripe tropical fruit is best fresh.",
    },
    {
      id: "b4",
      category: "breakfast",
      name: "Liver & Eggs Hash",
      tags: ["organs", "highpro", "highfat", "saladino", "peat"],
      time: "20 min",
      why: "Liver weekly is non-negotiable in this framework. Paired with eggs and butter, it becomes a complete nutrient delivery meal — retinol, copper, B12, choline all in one pan.",
      ingredients: [
        "3 oz beef or lamb liver, thin-sliced",
        "2 whole eggs",
        "1 tbsp butter + 1 tbsp tallow",
        "½ cup diced potato (pre-boiled)",
        "Sea salt",
        "Optional: squeeze of orange juice over liver while cooking",
      ],
      method: "Render tallow in a cast iron pan. Add pre-boiled potato cubes — cook until golden. Push aside. Add butter, sear liver 90 seconds per side (still slightly pink inside). Fry eggs in remaining fat. Plate together. Season well.",
    },
    {
      id: "b5",
      category: "breakfast",
      name: "Milk & Honey Porridge (White Rice)",
      tags: ["quick", "dairy", "fruit", "peat"],
      time: "15 min",
      why: "Peat's rice preference in action. White rice is the cleanest grain — fully digestible, no antinutrients. Cooked in whole milk, sweetened with honey, it becomes a pro-metabolic porridge.",
      ingredients: [
        "½ cup white rice (jasmine or basmati)",
        "1½ cups whole milk",
        "1 tbsp raw honey",
        "1 tsp butter",
        "Pinch of sea salt",
        "Optional: fresh mango or berries on top",
      ],
      method: "Combine rice and milk in a small saucepan. Cook over medium-low heat, stirring frequently, until rice absorbs milk (12–14 min). Stir in butter and honey. Top with fruit.",
    },
    {
      id: "b6",
      category: "breakfast",
      name: "Cottage Cheese + Fruit Plate",
      tags: ["quick", "dairy", "fruit", "highpro", "peat"],
      time: "3 min",
      why: "Fast protein + natural sugar. Cottage cheese is casein-based and easy on digestion. The fruit provides quick metabolic fuel. A true Peat-aligned speed meal.",
      ingredients: [
        "¾ cup full-fat cottage cheese",
        "1 cup mixed ripe fruit (mango, cherries, peaches)",
        "1 tbsp honey",
        "Pinch of sea salt",
      ],
      method: "Spoon cottage cheese into a bowl. Arrange fruit alongside or on top. Drizzle honey, add salt. Done.",
    },
    {
      id: "b7",
      category: "breakfast",
      name: "Oyster Omelette",
      tags: ["shellfish", "highpro", "dairy", "saladino"],
      time: "12 min",
      why: "A zinc + choline bomb. Oysters and eggs together cover the full mineral spectrum most people lack. Butter-cooked for saturated fat.",
      ingredients: [
        "4 pasture-raised eggs",
        "4–6 oysters (canned smoked or fresh, shucked)",
        "1 tbsp butter",
        "1 oz parmesan, grated",
        "Sea salt",
        "Fresh lemon juice",
      ],
      method: "Beat eggs with salt. Melt butter over medium. Pour in eggs. As eggs set, add oysters and parmesan to one half. Fold. Finish with lemon juice over oysters.",
    },

    // ── LUNCH ─────────────────────────────────────────────
    {
      id: "l1",
      category: "lunch",
      name: "Beef & Bone Broth Bowl",
      tags: ["gelatin", "highpro", "highfat", "peat", "saladino"],
      time: "15 min",
      why: "Muscle meat balanced by gelatin from broth — the glycine/methionine balance Peat emphasized. Add white rice for clean carbohydrate and potassium from sweet potato.",
      ingredients: [
        "5–6 oz grass-fed ground beef or thinly sliced ribeye",
        "1 cup homemade bone broth",
        "½ cup cooked white rice",
        "1 tbsp butter",
        "Sea salt",
        "Optional: ½ cup cooked sweet potato",
      ],
      method: "Cook beef in butter over medium-high — season well. Heat broth separately, add gelatin powder if store-bought. Build bowl: rice base, beef, ladle broth over everything. Add sweet potato.",
    },
    {
      id: "l2",
      category: "lunch",
      name: "Shrimp & Butter over Rice",
      tags: ["shellfish", "quick", "highpro", "saladino", "peat"],
      time: "12 min",
      why: "Shrimp is one of the cleanest seafood proteins — low PUFA, high iodine, selenium, and astaxanthin. Pan-seared in tallow or butter and served over white rice is simple and complete.",
      ingredients: [
        "6–8 oz shrimp, peeled",
        "1½ tbsp butter or tallow",
        "¾ cup cooked white rice",
        "Juice of ½ orange or lemon",
        "Sea salt, pinch of cayenne",
        "Fresh parsley (optional)",
      ],
      method: "Pat shrimp dry. Sear in hot tallow/butter 2 min per side. Squeeze citrus over pan, swirl into butter sauce. Serve over rice, pour pan sauce on top.",
    },
    {
      id: "l3",
      category: "lunch",
      name: "Cheese & Fruit Plate (The Peat Snack Meal)",
      tags: ["quick", "dairy", "fruit", "peat"],
      time: "3 min",
      why: "Peat often talked about the calcium-sugar pairing — cheese slows sugar absorption, milk calcium acts as a metabolic accelerant. This is that principle as a proper meal.",
      ingredients: [
        "3 oz aged cheddar, parmesan, or gruyère",
        "1 ripe mango or 1 cup watermelon cubes",
        "Handful of cherries or grapes",
        "2 dates",
        "Optional: 1 cup OJ or whole milk",
      ],
      method: "Slice cheese. Arrange fruit alongside. Eat together — alternate bites of cheese and fruit. Drink OJ or milk alongside.",
    },
    {
      id: "l4",
      category: "lunch",
      name: "Oxtail Soup",
      tags: ["gelatin", "highfat", "highpro", "peat", "saladino"],
      time: "3–4 hrs",
      why: "The ultimate gelatin delivery vehicle. Oxtail slow-cooked releases collagen that turns the broth to jelly when chilled — proof of glycine content. Rich, deeply satisfying, pro-metabolic.",
      ingredients: [
        "2–3 lbs oxtail sections",
        "2 medium carrots",
        "1 medium potato, cubed",
        "Sea salt generously",
        "2 tbsp tallow or butter (to brown)",
        "Water to cover",
      ],
      method: "Brown oxtail in tallow in a large pot. Cover with water, bring to boil, skim foam. Reduce to bare simmer. Cook 3–4 hrs until meat falls off bone. Add carrot and potato last 45 min. Salt aggressively. Broth should gel when cooled.",
    },
    {
      id: "l5",
      category: "lunch",
      name: "Smoked Oysters on Potatoes",
      tags: ["shellfish", "quick", "saladino"],
      time: "10 min",
      why: "Smoked canned oysters (in water or olive oil — check for seed oils) over boiled potato is a nutrient-dense fast lunch. Zinc, potassium, B12, selenium all in one plate.",
      ingredients: [
        "1 tin smoked oysters (Crown Prince — in olive oil or water)",
        "2 medium potatoes, boiled",
        "1 tbsp butter",
        "Sea salt and fresh lemon",
        "Optional: hot sauce",
      ],
      method: "Boil potatoes until fork-tender. Halve and mash slightly with butter and salt. Top with drained oysters. Squeeze lemon over everything.",
    },
    {
      id: "l6",
      category: "lunch",
      name: "Lamb Chops & Root Mash",
      tags: ["highfat", "highpro", "saladino"],
      time: "20 min",
      why: "Lamb is one of the best ruminant options — CLA, conjugated linoleic acid, B12, zinc. Paired with a carrot-potato mash it hits the Saladino animal-based ideal cleanly.",
      ingredients: [
        "2–3 lamb loin chops",
        "1 tbsp tallow or butter for searing",
        "1 large carrot + 1 medium potato, boiled",
        "2 tbsp butter for mash",
        "Sea salt",
        "Fresh rosemary",
      ],
      method: "Salt chops heavily, rest 10 min. Sear in screaming-hot tallow 3 min per side for medium-rare. Rest 5 min. Mash carrot and potato with butter. Plate and rest lamb on top of mash.",
    },
    {
      id: "l7",
      category: "lunch",
      name: "Milk + Gelatin Shake",
      tags: ["quick", "dairy", "gelatin", "fruit", "peat"],
      time: "3 min",
      why: "A drinkable meal straight from Peat's actual daily habits. Protein from milk, glycine from gelatin, sugar from fruit — the three pillars in one glass.",
      ingredients: [
        "1½ cups whole milk (cold)",
        "1 tbsp gelatin or collagen peptides",
        "1 ripe banana or ½ cup mango",
        "1 tbsp raw honey",
        "Pinch of sea salt",
        "Optional: 1 tsp cocoa powder",
      ],
      method: "Blend everything until smooth. If using gelatin (not collagen peptides), bloom in ¼ cup warm water first, then blend into cold milk.",
    },

    // ── DINNER ────────────────────────────────────────────
    {
      id: "d1",
      category: "dinner",
      name: "Ribeye with Bone Marrow Butter",
      tags: ["highfat", "highpro", "saladino", "peat"],
      time: "20 min",
      why: "Grass-fed ribeye is the flagship Saladino meal. Bone marrow adds alkylglycerols and concentrated saturated fat. The fat-to-protein ratio here is high — exactly what both frameworks want.",
      ingredients: [
        "1 grass-fed ribeye steak (12–16 oz, 1.5\" thick)",
        "2 tbsp tallow for searing",
        "1–2 tbsp bone marrow butter (or plain grass-fed butter)",
        "Coarse sea salt",
        "Optional: 1 cup OJ to drink",
      ],
      method: "Salt steak 1 hr ahead. Bring to room temp. Sear in screaming-hot cast iron with tallow, 3–4 min per side. Baste with butter last minute. Rest 8 min. Top with bone marrow butter before serving.",
    },
    {
      id: "d2",
      category: "dinner",
      name: "Braised Short Ribs",
      tags: ["gelatin", "highfat", "highpro", "saladino", "peat"],
      time: "3.5 hrs",
      why: "Short ribs are connective tissue-rich — slow braising releases collagen into the braising liquid, turning it into a gelatin-dense sauce. The ultimate glycine-rich dinner.",
      ingredients: [
        "3 lbs bone-in short ribs",
        "2 tbsp tallow",
        "1 cup bone broth",
        "Sea salt heavily",
        "2 carrots, roughly cut",
        "1 tbsp tomato paste (optional, adds depth)",
      ],
      method: "Salt ribs generously, brown in tallow all sides in Dutch oven. Add broth, carrots, tomato paste. Cover and braise at 300°F for 3 hrs until fall-off-bone tender. Serve with braising liquid reduced to a sauce.",
    },
    {
      id: "d3",
      category: "dinner",
      name: "Liver & Onions with Butter",
      tags: ["organs", "highpro", "peat", "saladino"],
      time: "15 min",
      why: "The classic organ preparation. Beef liver cooked quickly over high heat stays tender and nutritious — overcooked liver is the main reason people avoid it. Butter and onion mask any strong flavor.",
      ingredients: [
        "4–5 oz beef or calf liver, sliced ¼\" thick",
        "2 tbsp grass-fed butter",
        "1 medium onion, thinly sliced",
        "Sea salt",
        "Splash of OJ or lemon (brightens the liver)",
        "White rice or potato on the side",
      ],
      method: "Caramelize onions in 1 tbsp butter over medium, 15 min until golden. Set aside. Increase heat to high, add remaining butter. Sear liver 60–90 seconds per side — it should be pink inside. Top with onions, squeeze citrus over.",
    },
    {
      id: "d4",
      category: "dinner",
      name: "Whole Roast Chicken with Tallow",
      tags: ["highfat", "highpro", "gelatin", "saladino"],
      time: "90 min",
      why: "Saladino includes pasture-raised chicken — prioritize thighs and legs (fattier, more forgiving). Roasting whole lets you make broth from the carcass immediately after.",
      ingredients: [
        "1 whole pasture-raised chicken (3–4 lbs)",
        "3 tbsp beef tallow or butter",
        "Sea salt generously",
        "Optional: stuff with lemon halves and garlic",
      ],
      method: "Pat chicken dry, rub all over with tallow, salt aggressively. Roast at 425°F for 60–75 min until 165°F internal at thigh. Rest 15 min before carving. Save carcass for broth.",
    },
    {
      id: "d5",
      category: "dinner",
      name: "Crab in Butter",
      tags: ["shellfish", "highfat", "highpro", "saladino"],
      time: "15 min",
      why: "Crab legs are one of the cleanest, highest-zinc seafoods available. The simplest preparation — steamed or baked, with pure butter — is also the most nutritionally honest.",
      ingredients: [
        "1.5–2 lbs king or snow crab legs",
        "4 tbsp grass-fed butter, melted",
        "Lemon wedges",
        "Sea salt",
        "Optional: 1 cup bone broth to steam in",
      ],
      method: "Steam crab legs 5–7 min until heated through (if pre-cooked). Or bake at 375°F for 10 min in a covered dish with butter. Serve with melted butter and lemon.",
    },
    {
      id: "d6",
      category: "dinner",
      name: "Beef Heart Steak",
      tags: ["organs", "highpro", "saladino", "peat"],
      time: "15 min",
      why: "Beef heart has more CoQ10 than any other food. It cooks exactly like steak — same technique, better nutrient profile. One of Saladino's recommended regular organ meals.",
      ingredients: [
        "5–6 oz beef heart, sliced into ½\" steaks",
        "1 tbsp tallow",
        "Sea salt",
        "Squeeze of lemon",
        "White rice or roasted potato alongside",
      ],
      method: "Slice heart against the grain into thick steaks. Season aggressively. Sear in hot tallow 2–3 min per side — keep it medium-rare, it toughens when overdone. Rest, then slice thin. Squeeze lemon.",
    },
    {
      id: "d7",
      category: "dinner",
      name: "Lamb Meatballs in Bone Broth",
      tags: ["gelatin", "highpro", "highfat", "saladino"],
      time: "30 min",
      why: "Ground lamb meatballs cooked in broth is the glycine-balance move — muscle meat + gelatin-rich broth in the same dish. High-zinc, high-fat, complete.",
      ingredients: [
        "1 lb ground lamb",
        "1 egg",
        "Sea salt",
        "2 cups homemade bone broth",
        "1 tbsp butter",
        "Optional: cooked rice to add to broth",
      ],
      method: "Mix lamb with egg and salt. Form into 1.5\" balls. Sear in butter all sides, 4–5 min. Pour broth over, simmer covered 15 min. Serve as a soup or over rice.",
    },
    {
      id: "d8",
      category: "dinner",
      name: "Baked Cod with Butter & Lemon",
      tags: ["highpro", "quick", "peat", "saladino"],
      time: "18 min",
      why: "White fish (cod, sole, halibut) is Peat-approved seafood — low PUFA, clean protein, iodine, selenium. Simple baked with butter keeps it maximally nutritious.",
      ingredients: [
        "6–8 oz wild cod fillet",
        "2 tbsp grass-fed butter, sliced",
        "Lemon juice",
        "Sea salt",
        "Optional: serve over mashed potato",
      ],
      method: "Place cod in a baking dish. Top with butter slices, lemon juice, and salt. Bake at 400°F for 12–15 min until flesh flakes. Serve immediately.",
    },

    // ── SNACKS & DRINKS ──────────────────────────────────
    {
      id: "s1",
      category: "snack",
      name: "The Peat Protocol Coffee",
      tags: ["quick", "dairy", "gelatin", "peat"],
      time: "5 min",
      why: "Peat's most documented daily habit. Coffee is anti-estrogenic, stimulates bile flow, and is pro-thyroid when consumed with milk and sugar. Gelatin turns it into a glycine delivery vehicle.",
      ingredients: [
        "1 cup strong coffee",
        "¼ cup whole milk or heavy cream",
        "1 tsp cane sugar or raw honey",
        "1 tbsp collagen peptides (dissolves cold) or gelatin",
        "Pinch of sea salt",
      ],
      method: "Brew coffee. Stir in collagen peptides until dissolved. Add milk, sweeten. Salt if desired. Drink hot.",
    },
    {
      id: "s2",
      category: "snack",
      name: "Cheese + Dates",
      tags: ["quick", "dairy", "fruit", "peat"],
      time: "2 min",
      why: "Calcium + sucrose pairing. Peat's fat-and-sugar idea in snack form — the cheese slows digestion of the date's sugar while delivering K2 and protein.",
      ingredients: [
        "2–3 medjool dates, pitted",
        "2 oz aged cheddar or parmesan",
      ],
      method: "Slice cheese, eat with dates. Optionally stuff date with a small piece of cheese.",
    },
    {
      id: "s3",
      category: "snack",
      name: "Gelatin Gummies (OJ + Honey)",
      tags: ["gelatin", "fruit", "peat", "quick"],
      time: "10 min + chill",
      why: "The most popular Peat community preparation. Gelatin sets with OJ and honey into gummies that are a convenient, portable glycine source. Refrigerate and snack throughout the day.",
      ingredients: [
        "2 cups fresh-squeezed orange juice",
        "3 tbsp gelatin powder",
        "2 tbsp raw honey",
        "Pinch of sea salt",
      ],
      method: "Warm OJ gently (not boiling). Sprinkle gelatin over, whisk until dissolved. Add honey and salt. Pour into a container or molds. Refrigerate 2+ hrs until set. Cut into cubes.",
    },
    {
      id: "s4",
      category: "snack",
      name: "Whole Milk with Honey & Salt",
      tags: ["quick", "dairy", "peat"],
      time: "1 min",
      why: "Peat's simplest recommendation. Salt potentiates calcium absorption. Honey adds sucrose. Together they create a genuinely pro-metabolic drink — not just calories.",
      ingredients: [
        "1 cup cold whole milk (raw or grass-fed)",
        "1 tsp raw honey",
        "Small pinch of sea salt",
      ],
      method: "Stir honey and salt into cold milk. Drink.",
    },
    {
      id: "s5",
      category: "snack",
      name: "Smoked Oysters + Hot Sauce",
      tags: ["quick", "shellfish", "saladino"],
      time: "2 min",
      why: "Canned smoked oysters are one of the most nutrient-dense convenience foods available. Zinc, B12, selenium, copper — all bioavailable. Crown Prince in olive oil or water only.",
      ingredients: [
        "1 tin Crown Prince smoked oysters (water or olive oil)",
        "Hot sauce (Frank's, Cholula — check for seed oils)",
        "Squeeze of lemon",
      ],
      method: "Drain. Add hot sauce and lemon. Eat directly from the tin or on a plate.",
    },
    {
      id: "s6",
      category: "snack",
      name: "Watermelon + Sea Salt",
      tags: ["quick", "fruit", "peat", "saladino"],
      time: "2 min",
      why: "Saladino eats watermelon daily. Lycopene, citrulline, potassium. Salt amplifies sweetness and adds sodium for metabolic support.",
      ingredients: [
        "2–3 cups watermelon, cubed",
        "Flaky sea salt",
        "Optional: squeeze of lime",
      ],
      method: "Cut. Salt. Eat immediately.",
    },
    {
      id: "s7",
      category: "snack",
      name: "Ice Cream (Peat-approved)",
      tags: ["dairy", "fruit", "peat"],
      time: "2 min",
      why: "Peat specifically listed ice cream as a healthful food — saturated fat + calcium + sugar in a metabolically useful ratio. Use a brand with only cream, milk, sugar, egg yolks — no gums, no seed oils.",
      ingredients: [
        "1–2 scoops quality vanilla ice cream",
        "Optional: drizzle of honey",
        "Optional: ripe cherries or mango on top",
      ],
      method: "Scoop. Top with fruit. Eat without guilt — this is the protocol.",
    },
    {
      id: "s8",
      category: "snack",
      name: "Raw Carrot Salad (Peat Protocol)",
      tags: ["quick", "peat"],
      time: "5 min",
      why: "One of Peat's most specific recommendations. Raw carrot's insoluble fiber is uniquely antimicrobial and binds endotoxin and excess estrogen in the gut. Coconut oil + salt is the standard dressing.",
      ingredients: [
        "1 medium raw carrot, peeled and grated",
        "1 tsp coconut oil (melted) or olive oil",
        "Pinch of sea salt",
        "Splash of apple cider vinegar (optional)",
      ],
      method: "Grate carrot coarsely. Toss with oil and salt. Eat once daily — ideally between meals on an empty-ish stomach.",
    },

    // ── SIDES & EXTRAS ────────────────────────────────────
    {
      id: "x1",
      category: "sides",
      name: "Bone Broth (Base Recipe)",
      tags: ["gelatin", "peat", "saladino"],
      time: "8–12 hrs",
      why: "The glycine foundation of this whole framework. Make a big batch weekly. Should gel solid when refrigerated — that's the test of collagen content. Use in everything.",
      ingredients: [
        "2–3 lbs mixed beef bones (knuckles, feet, marrow bones)",
        "2 tbsp apple cider vinegar (draws minerals)",
        "Sea salt",
        "Water to cover",
        "Optional: carrot, oxtail for extra gelatin",
      ],
      method: "Place bones in a large pot or slow cooker. Add ACV and cold water to cover. Bring to boil, skim foam. Reduce to bare simmer. Cook 8–12 hrs. Strain. Salt generously. Refrigerate — fat cap rises and gels firm underneath.",
    },
    {
      id: "x2",
      category: "sides",
      name: "Butter-Roasted Sweet Potato",
      tags: ["quick", "highfat", "peat", "saladino"],
      time: "45 min",
      why: "Dense potassium, beta-carotene, easy starch. Butter dramatically improves beta-carotene absorption. Simple side that works with every protein in this framework.",
      ingredients: [
        "2 medium sweet potatoes",
        "2 tbsp grass-fed butter",
        "Sea salt",
        "Optional: drizzle of honey post-roast",
      ],
      method: "Roast whole at 400°F for 40–45 min until soft. Slice open, press in butter, salt generously. Optional honey drizzle ties it to the fruit-sugar principle.",
    },
    {
      id: "x3",
      category: "sides",
      name: "Peat's Raw Carrot Salad",
      tags: ["quick", "peat"],
      time: "5 min",
      why: "Repeated here as a side — pair it with any high-protein main. The antimicrobial, estrogen-binding properties of raw carrot work best eaten alongside or just after protein meals.",
      ingredients: [
        "1–2 raw carrots, grated",
        "1 tsp coconut oil",
        "Pinch of sea salt",
        "Splash of apple cider vinegar",
      ],
      method: "Grate, toss, serve fresh. Don't make in advance — eat within 20 min of grating.",
    },
    {
      id: "x4",
      category: "sides",
      name: "Coconut Oil Fried Potatoes",
      tags: ["highfat", "peat"],
      time: "20 min",
      why: "Coconut oil is the correct frying fat — near-zero PUFA, high smoke point. Fried potatoes in coconut oil are a Peat forum staple. Pair with any protein.",
      ingredients: [
        "2 medium potatoes, cubed or sliced thin",
        "3 tbsp coconut oil",
        "Sea salt",
        "Optional: garlic, rosemary",
      ],
      method: "Heat coconut oil over medium-high until shimmering. Add potatoes in a single layer. Don't stir for 4–5 min — let a crust form. Flip, cook another 4–5 min until golden. Salt immediately.",
    },
    {
      id: "x5",
      category: "sides",
      name: "Milk & Honey Jelly (Gelatin Set)",
      tags: ["gelatin", "dairy", "peat"],
      time: "5 min + chill",
      why: "Peat community variation: set whole milk and honey with gelatin into a panna-cotta style dessert or snack. Protein + calcium + glycine in a portable, snackable form.",
      ingredients: [
        "2 cups whole milk",
        "1.5 tbsp gelatin powder",
        "2 tbsp raw honey",
        "Pinch of sea salt",
        "Vanilla extract (optional)",
      ],
      method: "Warm milk gently. Whisk in gelatin until dissolved. Add honey, salt, vanilla. Pour into cups or a container. Refrigerate 2+ hrs until set. Eat cold.",
    },
    {
      id: "x6",
      category: "sides",
      name: "Whipped Honey Butter",
      tags: ["quick", "dairy", "highfat", "peat"],
      time: "5 min",
      why: "A compound butter that goes on everything — potatoes, meat, rice, toast. Butter + honey is the Peat fat-sugar pairing in condiment form.",
      ingredients: [
        "4 tbsp softened grass-fed butter",
        "1 tbsp raw honey",
        "Pinch of sea salt",
      ],
      method: "Beat butter with a fork until fluffy. Mix in honey and salt. Refrigerate or use immediately. Goes on everything.",
    },

    // ── COMMUNITY SUBMISSIONS ─────────────────────────
    {
      id: "c1",
      category: "breakfast",
      name: "OJ Gelatin Jelly",
      tags: ["quick", "gelatin", "fruit", "peat"],
      time: "10 min + 2 hr chill",
      community: true,
      source: "r/raypeat community",
      sourceUrl: "https://www.reddit.com/r/raypeat/",
      why: "One of the most shared recipes across r/raypeat and the wider Peat community. A portable, snackable glycine delivery method that tastes genuinely good. Set it in the fridge the night before.",
      ingredients: [
        "2 cups fresh-squeezed orange juice",
        "2 tbsp bovine gelatin powder",
        "¼ cup boiling water",
        "1 tbsp raw honey",
        "Pinch of sea salt",
      ],
      method: "Bloom gelatin in 2 tbsp cold water for 2 minutes. Pour ¼ cup boiling water over, stir until dissolved. Combine with OJ, honey, and salt. Pour into a shallow dish or silicone molds. Refrigerate 2–3 hrs until set. Cut into cubes. Keep refrigerated.",
    },
    {
      id: "c2",
      category: "snack",
      name: "Cheese & OJ (The Lazy Peat Meal)",
      tags: ["quick", "dairy", "fruit", "peat"],
      time: "2 min",
      community: true,
      source: "r/raypeat community",
      sourceUrl: "https://www.reddit.com/r/raypeat/",
      why: "Legendary shortcut in the Peat community — cited repeatedly in forum threads as the go-to when you have no time and need something that 'nails everything.' Calcium from cheese, sugar and potassium from OJ. Not glamorous. Incredibly effective.",
      ingredients: [
        "2–3 oz aged cheddar or parmesan",
        "6–8 oz fresh-squeezed orange juice",
      ],
      method: "Pour OJ. Slice cheese. Eat together. That's it. The community calls this 'the Peat cheat code.'",
    },
    {
      id: "c3",
      category: "breakfast",
      name: "Milk Collagen Smoothie",
      tags: ["quick", "dairy", "gelatin", "fruit", "peat"],
      time: "3 min",
      community: true,
      source: "r/raypeat community",
      sourceUrl: "https://www.reddit.com/r/raypeat/",
      why: "A popular variation from the Low-Toxin Bioenergetic Forum and r/raypeat — a portable meal that hits protein, glycine, calcium, and fruit sugar in one go. Keeps well in a vacuum flask for work.",
      ingredients: [
        "2 cups whole milk (cold)",
        "2 cups frozen fruit (berries, banana, mango — your pick)",
        "2–4 scoops Great Lakes collagen or gelatin",
        "2 tsp raw honey or cane sugar",
        "Pinch of sea salt",
      ],
      method: "If using gelatin (not collagen peptides), bloom in 2 tbsp warm water first. Add everything to a blender. Blend until smooth. Pour into a flask for work or drink immediately.",
    },
    {
      id: "c4",
      category: "breakfast",
      name: "Saladino's Pre-Surf Plate",
      tags: ["quick", "highpro", "fruit", "saladino"],
      time: "5 min",
      community: true,
      source: "Paul Saladino (@carnivoremd2 on X)",
      sourceUrl: "https://x.com/carnivoremd2",
      why: "Paul Saladino's documented pre-activity meal — shared across his social channels. Small, fast-digesting, sets him up before surfing. The raw egg yolks add fat-soluble vitamins without weighing you down.",
      ingredients: [
        "2 raw egg yolks",
        "1–2 tbsp raw honey",
        "½ cup ripe mango or banana",
        "Small pinch of sea salt",
      ],
      method: "Combine in a small bowl or just eat side-by-side. Yolks provide fat-soluble vitamins, fruit provides fast glucose for energy. No cooking — intentionally.",
    },
    {
      id: "c5",
      category: "lunch",
      name: "Ground Beef Taco Bowl with Gelatin Broth",
      tags: ["highpro", "gelatin", "dairy", "peat"],
      time: "20 min",
      community: true,
      source: "Ivy Herbal / r/raypeat community",
      sourceUrl: "https://www.ivyherbal.com/articles/ray-peat-dinner-ideas",
      why: "A community adaptation that solves the glycine-balance problem in a weeknight-friendly way — stir gelatin directly into the beef as it cooks, no broth required. Inspired by a widely-shared Ivy Herbal recipe and adapted by the Peat forum community.",
      ingredients: [
        "1 lb 80/20 ground beef",
        "1 tbsp tallow or butter",
        "1 tbsp unflavored gelatin, stirred into 2 tbsp warm bone broth or water",
        "Sea salt, oregano",
        "Corn tortillas (masa/nixtamalized) or white rice",
        "Shredded aged cheddar",
        "Cooked zucchini in butter on the side",
      ],
      method: "Brown beef in tallow with salt and oregano. Stir dissolved gelatin into cooked meat — it absorbs in seconds. Warm tortillas or serve over rice. Top with cheese. Side of butter-cooked zucchini.",
    },
    {
      id: "c6",
      category: "dinner",
      name: "Slow-Cooked Oxtail Soup",
      tags: ["gelatin", "highfat", "highpro", "peat", "saladino"],
      time: "4 hrs",
      community: true,
      source: "Ivy Herbal / Peat community",
      sourceUrl: "https://www.ivyherbal.com/articles/ray-peat-dinner-ideas",
      why: "Probably the most celebrated recipe in the Peat community — slow-cooked oxtail creates its own bone broth as it simmers. The test: refrigerate the broth overnight. If it gels solid, you've made something genuinely nourishing. Featured in multiple Peat recipe roundups.",
      ingredients: [
        "2–3 lbs oxtail sections",
        "2 tbsp beef tallow",
        "2 medium carrots (peeled)",
        "2 medium potatoes, cubed",
        "Well-cooked mushrooms (optional, add last 30 min)",
        "Sea salt generously",
        "Water to cover",
      ],
      method: "Brown oxtail in tallow in a large pot. Cover with water, bring to boil, skim foam. Reduce to bare simmer. Cook 3.5–4 hrs. Add carrots and potato in last 45 min, mushrooms in last 30 min. Salt aggressively — taste as you go. Broth should gel when cooled. Serve as soup or over white rice.",
    },
    {
      id: "c7",
      category: "snack",
      name: "Saladino's Daily Fruit & Honey Bowl",
      tags: ["quick", "fruit", "saladino"],
      time: "3 min",
      community: true,
      source: "Paul Saladino (@carnivoremd2 on X)",
      sourceUrl: "https://x.com/carnivoremd2",
      why: "Saladino's documented daily carbohydrate base — fruit and honey at every meal alongside meat. This is the carb portion of his animal-based protocol. He eats watermelon and mango daily and targets 150–180g of fruit carbs depending on activity level.",
      ingredients: [
        "200g ripe watermelon chunks",
        "200g ripe mango, cubed",
        "100g papaya (optional)",
        "1–2 tbsp raw honey",
        "Pinch of sea salt",
      ],
      method: "Combine, drizzle honey, add salt. Eat alongside any protein. The salt isn't decoration — it potentiates the sweetness and adds sodium for metabolic support.",
    },
    {
      id: "c8",
      category: "breakfast",
      name: "Raw Milk Yogurt with Fruit",
      tags: ["quick", "dairy", "fruit", "saladino"],
      time: "2 min",
      community: true,
      source: "Animal-based community / @carnivoremd2",
      sourceUrl: "https://x.com/carnivoremd2",
      why: "One of Saladino's explicitly recommended breakfast options — 'yogurt with fruit: raw yogurt is best.' Widely shared in the r/animalbased community as an accessible everyday breakfast. The fat in the yogurt slows sugar absorption; the fruit delivers potassium and vitamins.",
      ingredients: [
        "¾ cup whole milk yogurt (raw preferred, grass-fed second)",
        "1 cup ripe local fruit (berries, mango, peach — whatever's in season)",
        "1 tbsp raw honey",
        "Pinch of sea salt",
      ],
      method: "Spoon yogurt into a bowl. Top with fruit and honey. Salt. Eat immediately — don't let it sit or the fruit makes the yogurt watery.",
    },
  ],
};
